// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDytufzglWnfHRh5PEdzcbwxxOfTBEPLGE',
    appId: '1:360126584085:web:e3d8c02bd2de178d4cc51c',
    messagingSenderId: '360126584085',
    projectId: 'solution-challenge-704ed',
    authDomain: 'solution-challenge-704ed.firebaseapp.com',
    storageBucket: 'solution-challenge-704ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBidBfdJX1S9RzCFubA5UBHgJICBGFkH_0',
    appId: '1:360126584085:android:353d784b369fb1dc4cc51c',
    messagingSenderId: '360126584085',
    projectId: 'solution-challenge-704ed',
    storageBucket: 'solution-challenge-704ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwOejHFUL_aJ5QlmKDw7UMNnGXWGXnK6k',
    appId: '1:360126584085:ios:7f71a528ecbe99974cc51c',
    messagingSenderId: '360126584085',
    projectId: 'solution-challenge-704ed',
    storageBucket: 'solution-challenge-704ed.firebasestorage.app',
    iosBundleId: 'com.example.solutionChallenge',
  );
}
